### ISSUE TITLE
otsikko taustakuva

### ISSUE THREAD

**Issue by millakortelainen** [linkki/linkki-research#20]
Osioiden osoiden alkuun tarvisi kuvan. Kuva sijaitsee osion otsikon taustalla. Kuvan päällä oleva teksti pitäisi näkyä.

**Comment by lawkaita** [comment]
Onko taustakuvan tarkoitus täyttää koko alue headerin takana? Katso punainen alue kuvassa:
[https://www.mv.helsinki.fi/home/lawkaita/more/scrnsht.png](https://www.mv.helsinki.fi/home/lawkaita/more/scrnsht.png)

**Comment by millakortelainen** [comment]
Toinen vaihtoehto on tehdä kuvasta (ja headerista) materiaali tekstin levyinen. Vois kyllä olla hauska, että se ois koko sivun levyinen kun kyseessä on kuitenkin lasten materiaali, niin se tois siihen eläväisyyttä. Mun puolesta voit kyl ite päättää kumman haluut toteuttaa.
